version: "3"
services:
  frontend:
    container_name: fretex_frontend_dev
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/code
  backend:
    container_name: fretex_backend_dev
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.dev
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    container_name: fretex_postgres_dev
    image: postgres:13
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fretex
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



    
