version: "3"
services:
  node:
    container_name: fretex_node
    image: node:16
    working_dir: /code/frontend
    command: bash -c "npm install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  django:
    container_name: fretex_django
    build: ./docker/Dockerfile.django
    working_dir: /code/backend
    command: bash -c "gunicorn core.wsgi"
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - node
  postgres:
    container_name: fretex_postgres
    image: postgres:13
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fretex
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



    
